spring:
  application:
    name: check
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_clevertec_check
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8090